### ISSUE TITLE
D64-Diskwechsel wird nicht erkannt

### ISSUE THREAD

**Issue by fook42** [ThKattanek/1541-rebuild#33]
Problem, dass manche Loader (alle?) über die Floppy-ID im Header eines jeden Tracks erkennen, ob die gleiche Diskette noch im Laufwerk liegt oder eine andere (bzw. andere Seite) eingelegt wurde.
D64 enthält diese Information nicht - beim "generieren" der GCR-Daten wird immer die gleiche Floppy-ID weitergegeben.

**Comment by ThKattanek** [comment]
Erledigt durch fook42
